/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrimesCheckerRouteImport } from './routes/primes-checker'
import { Route as PrimeGeneratorRouteImport } from './routes/prime-generator'
import { Route as IndexRouteImport } from './routes/index'

const PrimesCheckerRoute = PrimesCheckerRouteImport.update({
  id: '/primes-checker',
  path: '/primes-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimeGeneratorRoute = PrimeGeneratorRouteImport.update({
  id: '/prime-generator',
  path: '/prime-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prime-generator': typeof PrimeGeneratorRoute
  '/primes-checker': typeof PrimesCheckerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prime-generator': typeof PrimeGeneratorRoute
  '/primes-checker': typeof PrimesCheckerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prime-generator': typeof PrimeGeneratorRoute
  '/primes-checker': typeof PrimesCheckerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/prime-generator' | '/primes-checker'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/prime-generator' | '/primes-checker'
  id: '__root__' | '/' | '/prime-generator' | '/primes-checker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrimeGeneratorRoute: typeof PrimeGeneratorRoute
  PrimesCheckerRoute: typeof PrimesCheckerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/primes-checker': {
      id: '/primes-checker'
      path: '/primes-checker'
      fullPath: '/primes-checker'
      preLoaderRoute: typeof PrimesCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prime-generator': {
      id: '/prime-generator'
      path: '/prime-generator'
      fullPath: '/prime-generator'
      preLoaderRoute: typeof PrimeGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrimeGeneratorRoute: PrimeGeneratorRoute,
  PrimesCheckerRoute: PrimesCheckerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
